SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `vote` (
  `id` int(11) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `value` int(11) DEFAULT NULL,
  `dataset` int(11) DEFAULT NULL,
  `date` timestamp NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `vote`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `vote`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;
